; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
extra_scripts = pre:pre_build_script.py
build_flags =        ; TEMPORARY TO GET RID OF INTELLISENSE ERRORS
    -D MODE_UART

[mode_uart]
build_flags = 
    -D MODE_UART

[mode_live]
build_flags =
    -D MODE_LIVE
