#pragma once

#define AUDIO_SAMPLE_RATE    16000
#define AUDIO_CHANNELS       1

#define ML_WINDOW_SIZE_MS    1000
#define ML_STRIDE_SIZE_MS    200

#define ML_WINDOW_SAMPLES    ((AUDIO_SAMPLE_RATE * ML_WINDOW_SIZE_MS) / 1000)
#define ML_STRIDE_SAMPLES    ((AUDIO_SAMPLE_RATE * ML_STRIDE_SIZE_MS) / 1000)


#define FFT_SIZE             512
#define FFT_HOP_SIZE         256 // 50% overlap

#define SPECTRUM_COLS        (FFT_SIZE / 2)
#define SPECTRUM_ROWS        ((ML_WINDOW_SAMPLES - FFT_SIZE) / FFT_HOP_SIZE + 1)
#define SPECTRUM_TOTAL_SIZE  (SPECTRUM_ROWS * SPECTRUM_COLS)


#define UART_PORT_NUM        UART_NUM_0
#define UART_TX_PIN          UART_PIN_NO_CHANGE
#define UART_RX_PIN          UART_PIN_NO_CHANGE